name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ feature/* ]

jobs:
  linux-build:
    name: linux-build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Compile
      run: |
        go install
        go vet ./...
        go build -o terraform-provider-redshift
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: terraform-provider-redshift_linux
        path: terraform-provider-redshift
        
  darwin-build:
    name: darwin-build
    runs-on: macos-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Compile
      run: |
        go install
        go vet ./...
        go build -o terraform-provider-redshift
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: terraform-provider-redshift_darwin
        path: terraform-provider-redshift

  windows-build:
    name: windows-build
    runs-on: windows-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Compile
      run: |
        go install
        go vet ./...
        go build -o terraform-provider-redshift
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: terraform-provider-redshift_windows
        path: terraform-provider-redshift
